### ISSUE TITLE
Indexing bug in OpenmcHeatDriver::init_temperatures

### ISSUE THREAD

**Issue by RonRahaman** [enrico-dev/enrico#66]
`OpenmcHeatDriver::init_temperatures` has the same bug that was fixed for `init_densities` in #65.  `ring_index` and `axial_index` are incorrectly incremented.  

https://github.com/enrico-dev/enrico/blob/b02681d279e9bd4803633915994e2e2d4fff8992/src/openmc_heat_driver.cpp#L274-L317

**Comment by aprilnovak** [comment]
I _think_ this one is fine... `ring_index` is only used for indexing in `ring_to_cell_inst_` - the bug from the other MR occurred because I incremented in the loop but then still used the value later on in the same loop. But I can change this loop to just be a loop for `ring_index` since `i`, `j`, and `k` aren't used otherwise.

**Comment by RonRahaman** [comment]
Ah right, I agree that it's not a bug here.  I'll remove the "bug" tag.  I would still like it changed to a "for" loop.

**Comment by paulromano** [comment]
@RonRahaman I think this can be closed. Do you concur?

**Comment by RonRahaman** [comment]
Yes, it can. Closing it now.
